name: Maven Package

on:
  push
  
env: 
  pass: secrets.GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: "echo '<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"\n    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n    xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0\n                        http://maven.apache.org/xsd/settings-1.0.0.xsd\">\n  \n    <activeProfiles>\n      <activeProfile>github</activeProfile>\n    </activeProfiles>\n  \n    <profiles>\n      <profile>\n        <id>github</id>\n        <repositories>\n          <repository>\n            <id>central</id>\n            <url>https://repo1.maven.org/maven2</url>\n          </repository>\n          <repository>\n            <id>github</id>\n            <url>https://maven.pkg.github.com/begonaguereca/maven-packages</url>\n            <snapshots>\n              <enabled>true</enabled>\n            </snapshots>\n          </repository>\n        </repositories>\n      </profile>\n    </profiles>\n  \n    <servers>\n      <server>\n        <id>github</id>\n        <username>begonaguereca</username>\n        <password>${{ secrets.PAT }}</password>\n      </server>\n    </servers>\n  </settings>' > ~/.m2/settings.xml"
          
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/begonaguereca/maven-packages", "snapshots": { "enabled": "true" } }]'
          servers: '[{ "id": "github", "username": "begonaguereca", "password": "${{ secrets.PAT }}" }]'
  
      - name: View settings.xml
        run: cat ~/.m2/settings.xml 
      
      - name: Install with Maven
        run: mvn install -s ~/.m2/settings.xml 
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
